[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PKG_NAME"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["src"]

# (Optional later)
# [project.scripts]
# PKG_NAME-run = "PKG_NAME.cli:main"
